#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_PRIVATE_KEY=$4

if (($#
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
  fi
