#!/usr/bin/env bash
# Bash script that configures a server to the above requirements
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs.
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
